<!DOCTYPE html>
<header class="headerContainer">
        <img src="images/mainlogo_nobg.png" alt="Company Logo" width="300">
        <!-- Navigation -->
        <nav class="navContainer">
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="jobs.html">Jobs</a></li>
                <li><a href="apply.html">Apply Now</a></li>
                <li><a href="about.html">About</a></li>
                <li><a href="#">Resources</a></li>
                <li><a href="#">FAQ</a></li>
            </ul>
        </nav>
    </header>