<!DOCTYPE html>
<header class="headerContainer">
        <img src="images/mainlogo_nobg.png" alt="Company Logo" width="300">
        <!-- Navigation -->
        <nav class="navContainer">
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="jobs.php">Jobs</a></li>
                <li><a href="apply.php">Apply Now</a></li>
                <li><a href="about.php">About</a></li>
                <li><a href="login.php">Login</a></li>
            </ul>
        </nav>
    </header>